authors:
  geyslein:
    name: Ronny Gey
    description: project member
    avatar: https://avatars.githubusercontent.com/u/283309
    url: https://github.com/geyslein
  Daniel-Mietchen:
    name: Daniel Mietchen
    description: project member
    avatar: https://avatars.githubusercontent.com/u/465923
    url: https://github.com/Daniel-Mietchen
  okarras:
    name: Oliver Karras
    description: project member
    avatar: https://avatars.githubusercontent.com/u/5848876
    url: https://github.com/okarras
