# SECRETS
# https://woodpecker-ci.org/docs/usage/secrets
# CBTOKEN needs a codeberg access token as secret in woodpecker config
# CBMAIL with email address for git config
# SOURCEREPO must be replaced with the source repo
# DESTREPO must be replaced with the target codeberg pages repo
# CBUSERNAME must be replaced with the user/org

steps:
  build:
    when:
      event: [push, pull_request]
    # Use the official mkdocs container
    image: squidfunk/mkdocs-material
    environment:
      # secrets must be set in Woodpecker configuration
      TOKEN:
        from_secret: token
      MAIL:
        from_secret: mail
      CBUSERNAME:
        from_secret: cbusername
      SOURCEREPO:
        from_secret: sourcerepo
      DESTREPO:
        from_secret: destrepo
    commands:
      # Avoid permission denied errors
      - chmod -R a+w .
      # Set up git in a working way
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/$CBUSERNAME/$SOURCEREPO/site
      - git config --global user.email "$MAIL"
      - git config --global user.name "CI Builder"
      # clone and move the target repo
      - git clone -b pages https://codeberg.org/$CBUSERNAME/$DESTREPO.git site
      - chmod -R a+w site
      - cd site
      # Prepare for push
      - git remote set-url origin https://$TOKEN@codeberg.org/$CBUSERNAME/$DESTREPO.git
      - cd ..
      # Run mkdocs build stage with poetry
      - pip install poetry
      - poetry install
      - poetry run mkdocs build
      # Only needed for custom domains
      - cp domains site/.domains
      # Push to target
      - cd site
      - git add --all
      - git commit -m "Woodpecker CI mkdocs Build at $( env TZ=Europe/Berlin date +"%Y-%m-%d %X %Z" )"
      - git push -u origin pages