# build and deploy mkdocs to codeberg pages
# This assumes your code lives in one repo, and you have a <owner>/pages
# repo which will be used to host the built pages.

steps:
  build-docs:
    when:
      event: [push, pull_request]
    image: squidfunk/mkdocs-material
    commands:
      - pip install poetry
      - poetry install
      - poetry run mkdocs build -d site $MKDOCS_ARGS

  deploy-docs:
    when:
      event: [push, pull_request]
      branch: main
    image: alpine:latest
    environment:
      CBMAIL:
        from_secret: mail
      CBTOKEN:
        from_secret: token
    commands:
      - apk add --no-cache git
      - git config --global user.email "$CBMAIL"
      - git config --global user.name "CI Docs Builder"
      - mv domains site/.domains
      - git remote set-url origin https://$CBTOKEN@codeberg.org/find-software/site.git
      - git switch --orphan pages
      - cp -r site/* .
      - rm -rf site
      - git add --all
      - git commit -m "Update Docs ($(TZ=Europe/Berlin date +"%d.%m.%Y %Z")) [SKIP CI]" || exit 0
      - git push -f --set-upstream origin pages