# build and deploy mkdocs to codeberg pages
# This assumes your code lives in one repo, and you have a <owner>/pages
# repo which will be used to host the built pages.

steps:
  build-docs:
    when:
      event: [push, pull_request]
    # build the docs with mkdocs and add the .domains file for codeberg pages
    image: squidfunk/mkdocs-material
    commands:
      - pip install poetry
      - poetry run mkdocs build
      - echo -e 'find-software.org\ntheologe.codeberg.page\npages.theologe.codeberg.page' > site/.domains

  deploy-docs:
    when:
      event: [push, pull_request]
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: site
      repository_name: theologe/site
      branch: main
      ssh_key:
        from_secret: codeberg_push_from_ci_priv_key